---
- name: Ensure clean state (remove old monitoring folder)
  file:
    path: /opt/monitoring
    state: absent

- name: Create monitoring directory
  file:
    path: /opt/monitoring
    state: directory

- name: Create prometheus config directory
  file:
    path: /opt/monitoring/prometheus
    state: directory
    mode: '0755'

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: /opt/monitoring/docker-compose.yml

- name: Copy prometheus config
  template:
    src: prometheus.yml.j2
    dest: /opt/monitoring/prometheus/prometheus.yml
    mode: '0644'

- name: Copy alert rules
  copy:
    src: alert.rules.yml
    dest: /opt/monitoring/prometheus/alert.rules.yml

- name: Start monitoring stack
  command: docker compose up -d
  args:
    chdir: /opt/monitoring

#- name: Run Node Exporter
 # community.docker.docker_container:
  #  name: node_exporter
   # image: prom/node-exporter
    #state: started
    #restart_policy: always
    #ports:
     # - "9100:9100"
