- name: Full system deployment
  hosts: all
  become: true
  vars:
    docker_host: "unix:///var/run/docker.sock"
    nginx_port: 80
    db_name: diplomadb
    db_user: diplomauser
    db_password: supersecurepass123
  roles:
    - nginx
    - postgresql
    - firewall
    - adminer
    - docker
    - jenkins
    - monitoring
    - alertmanager
